-- qc_criteria seed — สร้างอัตโนมัติจาก parse_qc_template.py (ห้ามแก้มือ)
-- ใช้: wrangler d1 execute dstr-db --file=seed/qc_criteria_seed.sql  [--local|--remote]
-- idempotent: INSERT OR REPLACE ตาม criteria_id

INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-01', 'A', 'งานวัสดุปิดผิว / แผ่นลามิเนต (Surface & Laminate)', 1.0, 'แผ่น HMR ปิดผิวลามิเนต – การยึดติดด้วยกาวยาง', 'แผ่นลามิเนตติดแน่นเต็มพื้นที่ ไม่บวม ไม่ล่อน ไม่เป็นโพรง/กอง โดยเฉพาะที่ขอบและมุม; เคาะแล้วเสียงทึบสม่ำเสมอทั้งแผ่น', 'ตรวจด้วยสายตา + ใช้สันมือ/เหรียญเคาะทั่วแผ่นเน้นขอบ-มุม; ลูบฝ่ามือหาคลื่น/ฟอง', '[C] ลามิเนตบวม/ฟอง (blister), ล่อนแยกที่ขอบ (delamination), เป็นโพรงอากาศ/กอง, กาวเยิ้มออกตามร่อง', 'C', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-02', 'A', 'งานวัสดุปิดผิว / แผ่นลามิเนต (Surface & Laminate)', 2.0, 'ผิวหน้าลามิเนต – ตำหนิ/รอย', 'ผิวเรียบสม่ำเสมอ ไม่มีรอยขีดข่วน รอยบุบ รอยกดทับ คราบกาว; ทิศทางลาย (grain) ต่อเนื่องและถูกล็อตสีตามแบบ', 'ส่องไฟกราดเฉียง (raking light) หารอย/คลื่น; เทียบทิศทางลายและล็อตสีกับแบบ/ตัวอย่าง', '[M] รอยขีดข่วน, รอยบุบ, คราบกาว/คราบมือ, ลายสลับทิศ, สีเพี้ยนต่างล็อต', 'M', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-03', 'A', 'งานวัสดุปิดผิว / แผ่นลามิเนต (Surface & Laminate)', 3.0, 'ระยะร่องลามิเนต (Groove spacing)', 'ความกว้างร่องเท่ากันตลอดแนวตามแบบ คลาดเคลื่อน ≤ ±0.5 มม.; ร่องตรงได้แนว ลึกเท่ากัน ขอบร่องคม-คมไม่บิ่น', 'วัดด้วยเวอร์เนีย/ฟิลเลอร์เกจ หลายจุดต่อแนว; เล็งแนวร่องด้วยเอ็นดิ่ง/สายตา', '[M] ร่องกว้างไม่เท่ากัน, ร่องเบี้ยว/คดงอ, ตื้น-ลึกไม่เท่ากัน, ขอบร่องบิ่น/เสี้ยน', 'M', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-04', 'A', 'งานวัสดุปิดผิว / แผ่นลามิเนต (Surface & Laminate)', 4.0, 'การทำสีขอบลามิเนต', 'สีขอบกลมกลืนกับผิวลามิเนต ปิดขอบ HMR มิด ไม่เห็นเนื้อไม้/ขอบขาว; เรียบ ไม่เป็นเม็ด ไม่ย้อย', 'ตรวจด้วยสายตาในระยะ 30–50 ซม. ภายใต้แสงสว่างพอเพียง; ลูบมือ', '[M] เห็นเนื้อ HMR/ขอบขาว, สีเพี้ยนจากผิวหน้า, สีย้อย/เป็นเม็ด, ลูบแล้วสะดุด', 'M', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-05', 'B', 'งานขอบบาน & การ Dap (Edging & Sealing)', 5.0, 'ขอบบานติดแผ่น Edging band', 'Edging ติดแน่นตลอดแนว ไม่ล่อนที่ปลาย/มุม; ตัดเก็บ (trim) เรียบ ไม่คมบาดมือ; สี/ความหนากลมกลืน; ไม่มีกาวเยิ้ม', 'ใช้เล็บ/มือลูบตามขอบหาจุดล่อน เน้นปลายและมุมบาน', '[M] Edging ล่อน/แยกที่ปลาย, ตัดเก็บไม่เรียบ (เหลื่อม/เกิน), กาวเยิ้มเป็นเส้น, สีไม่ตรง, ขอบคม', 'M', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-06', 'B', 'งานขอบบาน & การ Dap (Edging & Sealing)', 6.0, 'ความเสมอของร่องหน้าบาน บน-ล่าง (Reveal)', 'ร่องระหว่างบานเท่ากันทั้งบน-ล่าง และซ้าย-ขวา ตามแบบ; ค่าต่างระหว่างร่อง ≤ 1 มม.; แนวบานเรียงได้ระดับ', 'วัดร่องด้วยฟิลเลอร์เกจ/เวอร์เนีย ที่ตำแหน่งบน-กลาง-ล่าง; เช็คแนวด้วยระดับน้ำ/เลเซอร์', '[C] ร่องบนกว้างล่างแคบ (สอบ/ผาย), ร่องซ้าย-ขวาไม่เท่า, บานเหลื่อมระดับ/เอียง', 'C', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-07', 'B', 'งานขอบบาน & การ Dap (Edging & Sealing)', 7.0, 'การ Dap ขอบ / ยาแนวซิลิโคน', 'เส้น dap เรียบ สม่ำเสมอ ความหนาเท่ากันตลอดแนว เก็บมุมเรียบร้อย; สีกลมกลืน; ไม่มีรอยนิ้ว ไม่ย้อย ไม่ขาดช่วง; อุดรอยต่อมิด', 'ตรวจด้วยสายตาตามแนวรอยต่อ ตู้-ผนัง และ top-ผนัง', '[M] เส้นหนา-บางไม่เท่า, มีรอยนิ้ว, ย้อย/เลอะนอกแนว, ขาดช่วง/ไม่เต็มร่อง, สีเหลือง/ไม่ตรง', 'M', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-08', 'C', 'งานทำสี (Painting & Spray Finish)', 8.0, 'การทำสีหน้าบาน', 'ผิวสีเรียบเนียนสม่ำเสมอทั้งบาน ไม่พอง ไม่เป็นเม็ด ไม่เป็นคลื่นส้มเกินเกณฑ์; เงา/ด้านสม่ำเสมอ; สีตรงตาม spec/code', 'ส่องไฟกราดเฉียงหาคลื่น/เม็ด; ลูบมือ; เทียบ color swatch', '[C] สีพอง/ฟอง, เม็ดฝุ่น (dust nib), คลื่นส้ม (orange peel), สีย้อย (sagging), เงาไม่สม่ำเสมอ, สีเพี้ยน', 'C', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-09', 'C', 'งานทำสี (Painting & Spray Finish)', 9.0, 'การทำสีขอบบาน + ขอบร่อง (ทุกด้าน)', 'ขอบบานทุกด้านและขอบร่องทำสีครบ ไม่มีจุดบาง/หลุด; เรียบ ไม่เป็นเสี้ยน; กลมกลืนกับหน้าบาน', 'ตรวจขอบทั้ง 4 ด้าน + ขอบร่อง ด้วยสายตาและลูบมือ', '[M] ขอบทำสีไม่ครบ/บาง, ขอบร่องเป็นเสี้ยน/สะดุด, สีขอบเพี้ยนจากหน้าบาน, สีย้อยที่ขอบ', 'M', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-10', 'C', 'งานทำสี (Painting & Spray Finish)', 10.0, 'การทำสีพ่น (Spray finish)', 'ฟิล์มสีหนาสม่ำเสมอ ปิดผิวมิดไม่เห็นรองพื้น; ไม่มีฝุ่น/ขน/แมลงติด; ไม่ย้อย ไม่เป็นละอองหยาบ; เก็บมุม-ร่องทั่วถึง', 'ส่องไฟกราด; ตรวจมุมอับ/ร่อง; ตรวจ overspray บนผิวข้างเคียง', '[M] ฝุ่น/ขนติดฟิล์ม, สีย้อย, ผิวทราย/ละอองหยาบ (dry spray), overspray เลอะส่วนอื่น, มุม-ร่องพ่นไม่ถึง', 'M', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-11', 'D', 'งานอุปกรณ์ฮาร์ดแวร์ & การติดตั้ง (Hardware & Fittings)', 11.0, 'มือจับสแตนเลส', 'ติดตั้งตรงแนว ระดับเดียวกันทุกบาน ตามตำแหน่ง/ระยะในแบบ; ยึดแน่นไม่โยก; ผิวไม่มีรอยขีดข่วน/คราบนิ้ว; รุ่น/ทิศทางถูกตาม spec', 'วัดระยะตำแหน่งเทียบแบบ; โยกทดสอบความแน่น; ส่องไฟตรวจผิว; เทียบระดับด้วยเลเซอร์/ระดับน้ำ', '[M] มือจับเอียง/ไม่ได้ระดับ, หลวม/โยก, รอยขีดข่วน/คราบนิ้ว, ตำแหน่งไม่ตรงแบบ, รูเจาะเยื้อง/เห็นรูเก่า', 'M', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-12', 'D', 'งานอุปกรณ์ฮาร์ดแวร์ & การติดตั้ง (Hardware & Fittings)', 12.0, 'บานพับลูกถ้วย (Cup hinge / Soft-close)', 'เปิด-ปิดลื่น soft-close ทำงานปกติ; บานปิดสนิทไม่อ้า; ปรับตั้ง 3 ทิศให้บานเสมอกัน; จำนวนบานพับเหมาะกับน้ำหนัก/ความสูงบาน', 'เปิด-ปิดทดสอบหลายครั้ง; ตรวจการปิดนุ่ม; ตรวจร่องบานหลังปรับ', '[C] บานตก/เอียง, ปิดไม่สนิท/เด้ง, soft-close ไม่ทำงาน, บานพับหลวม/มีเสียง, บานชนกันเวลาเปิด', 'C', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-13', 'D', 'งานอุปกรณ์ฮาร์ดแวร์ & การติดตั้ง (Hardware & Fittings)', 13.0, 'รางลิ้นชักรับข้าง (Side-mount slide)', 'ลิ้นชักเลื่อนเข้า-ออกลื่น ไม่ฝืด ไม่สะดุด; รางซ้าย-ขวาขนานได้ระดับ; ปิดสนิท/soft-close ทำงาน; รับน้ำหนักได้ตาม spec ไม่แอ่น มี stopper', 'ชักเข้า-ออกสุดหลายครั้ง; ทดลองใส่น้ำหนัก; ตรวจระดับหน้าลิ้นชัก', '[M] ฝืด/สะดุด/มีเสียง, รางเอียงหน้าลิ้นชักไม่ได้ระดับ, ปิดไม่สนิท, ดึงสุดแล้วหลุด, แอ่นเมื่อรับน้ำหนัก', 'M', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-14', 'D', 'งานอุปกรณ์ฮาร์ดแวร์ & การติดตั้ง (Hardware & Fittings)', 14.0, 'รางลิ้นชักรับล่าง (Undermount slide)', 'เลื่อนลื่น soft-close ทำงาน; รางซ่อนใต้ลิ้นชักไม่เห็นจากด้านหน้า; ก้นลิ้นชักล็อกแน่นกับราง; หน้าลิ้นชักเสมอแนวบานอื่น', 'ชักทดสอบ; ตรวจการล็อกก้นลิ้นชักกับราง; ตรวจ reveal หน้าลิ้นชัก', '[M] ก้นลิ้นชักหลวม/ขยับ, รางโผล่เห็นด้านหน้า, หน้าลิ้นชักเหลื่อมระดับ, ฝืด/ปิดไม่สนิท', 'M', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-15', 'D', 'งานอุปกรณ์ฮาร์ดแวร์ & การติดตั้ง (Hardware & Fittings)', 15.0, 'บานลิ้นชัก (Drawer front)', 'หน้าบานลิ้นชักได้ระดับเรียงแนวกับบานข้างเคียง; ร่อง reveal รอบเท่ากัน; ยึดแน่นกับกล่องลิ้นชักไม่โยก', 'ตรวจแนว/ร่องด้วยสายตา + วัด; โยกทดสอบ', '[M] หน้าลิ้นชักเอียง/ไม่ได้แนว, ร่องไม่เท่า, หลวม/โยก, ขอบ-สีตำหนิ', 'M', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-16', 'D', 'งานอุปกรณ์ฮาร์ดแวร์ & การติดตั้ง (Hardware & Fittings)', 16.0, 'รางเลื่อน / บานเลื่อนประตู (Sliding door & track)', 'บานเลื่อนลื่นตลอดแนว ไม่ฝืด ไม่ตก ไม่ครูดพื้น/กรอบ; รางบน-ล่างขนานได้แนว; บานปิดชนกันสนิทไม่มีช่องแสง; soft-close (ถ้ามี) ทำงาน', 'เลื่อนทดสอบเต็มระยะหลายครั้ง; ตรวจช่องระหว่างบานเมื่อปิด; ตรวจล้อ/ราง', '[C] เลื่อนฝืด/สะดุด, บานครูด/ตก, รางเบี้ยว, ปิดไม่ชนสนิทเห็นช่องแสง, ล้อมีเสียง', 'C', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-17', 'E', 'งานกระจก (Glass)', 17.0, 'งานกระจก', 'ไม่มีรอยร้าว/บิ่น/ขีดข่วน; ตัดได้ขนาดพอดีช่อง ขอบเจียรเรียบ (polished) ไม่คม; ติดตั้งแน่นไม่หลวมไม่สั่น; ระยะร่องรอบเท่ากัน; ไม่มีคราบกาว/ซิลิโคนเลอะ', 'ส่องไฟตรวจรอย; สัมผัสขอบตรวจความคม; เขย่าเบา ๆ ตรวจความแน่น', '[C] ร้าว/บิ่นที่มุม, ขีดข่วน, ขอบคม/เจียรไม่เรียบ, หลวม/สั่น, คราบซิลิโคน-กาวเลอะ, ระยะร่องไม่เท่า', 'C', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-18', 'F', 'งานไฟแสงสว่าง (Lighting)', 18.0, 'รางไฟ / โคมไฟ (Track / Fixture)', 'ติดตั้งแน่น ตรงแนว ตามตำแหน่งในแบบ; ติดทุกดวง อุณหภูมิสี (เช่น 3000K) และความสว่างตรง spec และเท่ากันทุกจุด; ซ่อนสายเรียบร้อย; สวิตช์/dimmer ทำงาน', 'เปิดทดสอบทุกดวง; เทียบอุณหภูมิสี/ความสว่าง; ตรวจการเก็บสาย', '[M] ดวงไม่ติด/กระพริบ, อุณหภูมิสีไม่เท่ากัน, ติดตั้งเอียง/ไม่ตรงแบบ, เห็นสายไฟ, dimmer ไม่ทำงาน', 'M', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-19', 'F', 'งานไฟแสงสว่าง (Lighting)', 19.0, 'เส้นไฟ Strip light (LED เส้น)', 'ติดในรางต่อเนื่อง แสงสม่ำเสมอ ไม่เห็นเม็ด LED ตามมุมมอง; ไม่มีช่วงมืด/ขาดช่วง; สีแสงเท่ากันตลอดเส้น; ซ่อนเส้น/หม้อแปลงไม่เห็นจากมุมใช้งาน; ติดแน่นไม่ล่อน', 'เปิดไฟดูตลอดแนวในระยะ/มุมใช้งานจริง; ตรวจรอยต่อระหว่างเส้น', '[M] เห็นเม็ด LED/hotspot, ช่วงมืด/ขาดช่วง, สีเพี้ยนเป็นช่วง, เส้นไฟล่อน/หลุด, เห็นเส้น-สายจากด้านหน้า, ไฟกระพริบ', 'M', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-20', 'G', 'งานตกแต่ง (Decorative Trim)', 20.0, 'การติดบัวผัง (Skirting / Base trim)', 'บัวแนบผนัง/ตู้ตลอดแนวไม่มีช่อง; ต่อมุม (45°/ชน) เรียบเนียนได้แนว; ระดับสม่ำเสมอ; รอยต่อ-ยาแนวเรียบร้อย; สี/ผิวกลมกลืน', 'ตรวจแนวชิดผนัง; ตรวจมุมต่อ; ตรวจระดับด้วยสายตา/ระดับน้ำ', '[Mn] บัวลอย/มีช่องกับผนัง, มุมต่อไม่สนิท/เหลื่อม, ระดับไม่เท่า, ยาแนวเลอะ, สีไม่ตรง', 'Mn', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-21', 'G', 'งานตกแต่ง (Decorative Trim)', 21.0, 'การติดคิ้วตกแต่งหน้าบาน (Decorative molding)', 'คิ้วติดแน่น ได้แนวตรง ขนานขอบบาน ระยะจากขอบเท่ากันทุกบานในชุดเดียวกัน; ต่อมุมเรียบเนียน; สี/ผิวเรียบ; สมมาตรกัน', 'วัดระยะคิ้วจากขอบเทียบบานอื่น; ตรวจมุมต่อ; ตรวจความตรง', '[Mn] คิ้วเบี้ยว/ไม่ขนาน, ระยะจากขอบไม่เท่ากันระหว่างบาน, มุมต่อเหลื่อม/มีช่อง, คิ้วล่อน, สีตำหนิ', 'Mn', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-22', 'H', 'ขนาด & มิติ (Dimension & Alignment)', 22.0, 'ขนาดหน้าบาน / ชิ้นส่วน (Dimension)', 'กว้าง × สูง × หนา ของหน้าบานและชิ้นส่วนตรงตามแบบ คลาดเคลื่อน ≤ ±1 มม. (หรือตามที่แบบกำหนด); ได้ฉาก 90°', 'วัดด้วยตลับเมตร/เวอร์เนียหลายจุด; ตรวจฉากด้วยฉากเหล็ก', '[C] ขนาดเกิน/ขาดจากแบบ, ไม่ได้ฉาก (บิดเป็นข้าวหลามตัด), ความหนาไม่ตรง spec', 'C', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-23', 'H', 'ขนาด & มิติ (Dimension & Alignment)', 23.0, 'ระยะร่อง/แนว Reveal โดยรวม', 'ร่องระหว่างบานทั้งชุดเท่ากันตามแบบ ค่าต่าง ≤ 1 มม.; แนวบานเรียงตรงทั้งแนวนอน-แนวตั้ง', 'วัดร่องทุกช่องด้วยฟิลเลอร์เกจ; เล็งแนวด้วยเลเซอร์', '[M] ร่องไม่เท่ากันทั้งชุด, แนวบานคด/ไม่ตรง', 'M', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-24', 'H', 'ขนาด & มิติ (Dimension & Alignment)', 24.0, 'ความได้ดิ่ง/ระดับ/ความมั่นคงของตู้', 'ตู้ตั้งได้ดิ่งและระดับ คลาดเคลื่อน ≤ 1–2 มม./ม.; ยึดติดผนัง/พื้นมั่นคง ไม่โยก ไม่ล้ม; top วางได้ระดับ', 'ระดับน้ำ/เลเซอร์ตรวจดิ่ง-ระดับ; โยกทดสอบความมั่นคง; ตรวจจุดยึดผนัง', '[C] ตู้เอียง/ไม่ได้ดิ่ง, โยก/ไม่ยึดผนัง, top ไม่ได้ระดับ, ฐานลอย', 'C', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-25', 'I', 'ภาพรวม & การส่งมอบ (General & Delivery)', 25.0, 'ความสะอาด & ความเรียบร้อยก่อนส่งมอบ', 'ปราศจากคราบกาว ฝุ่น สีเลอะ ลายนิ้วมือ และฟิล์ม/สติกเกอร์ที่ต้องลอกออก; ภายในตู้/ลิ้นชักสะอาด; เก็บเศษวัสดุ/สกรู/ขี้เลื่อยหมด', 'ตรวจด้วยสายตาทั้งภายนอก-ภายใน; เปิดทุกบาน/ลิ้นชัก', '[Mn] คราบกาว/สี, ฝุ่น/ขี้เลื่อยในตู้, ลายนิ้วมือบนผิวเงา/สแตนเลส, ฟิล์ม/สติกเกอร์ค้าง', 'Mn', 'TRUE');
INSERT OR REPLACE INTO qc_criteria (criteria_id, section, section_name, seq, item, acceptance, method, defects, defect_class, active) VALUES ('QC-26', 'I', 'ภาพรวม & การส่งมอบ (General & Delivery)', 26.0, 'การทำงานโดยรวม (Function & ความครบถ้วน)', 'ทุกบาน/ลิ้นชัก/บานเลื่อนเปิด-ปิดได้ปกติ ไม่ชนกัน; อุปกรณ์เสริม (ตะแกรง/ราว/ปลั๊ก) ติดครบและใช้งานได้; ครบทุกรายการตามแบบ/BOQ', 'ทดสอบการใช้งานทุกจุด; เช็คครบตาม checklist/แบบ', '[M] บานชนกัน, อุปกรณ์ขาด/ไม่ทำงาน, รายการไม่ครบตามแบบ', 'M', 'TRUE');
